<?php

declare(strict_types=1);

namespace Agenciafmd\Support\Faker;

use Faker\Provider\Base;
use InvalidArgumentException;

final class Provider extends Base
{
    /*
     * https://github.com/aalaap/faker-youtube/blob/master/src/Youtube.php
     * */

    public function youtubeId(): string
    {
        $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
            . 'abcdefghijklmnopqrstuvwxyz_-';

        $id = mb_substr(self::shuffle($characters), 0, 11);

        return $this->generator->parse($id);
    }

    public function youtubeUri(): string
    {
        return 'https://www.youtube.com/watch?v=' . $this->youtubeId();
    }

    public function youtubeShortUri(): string
    {
        return 'https://youtu.be/' . $this->youtubeId();
    }

    public function youtubeEmbedUri(): string
    {
        return 'https://www.youtube.com/embed/' . $this->youtubeId();
    }

    public function youtubeEmbedCode(): string
    {
        return '<iframe width="560" height="315" src="' . $this->youtubeEmbedUri()
            . '" frameborder="0" gesture="media" allow="encrypted-media"'
            . ' allowfullscreen></iframe>';
    }

    public function youtubeChannelUri(): string
    {
        return sprintf('https://www.youtube.com/%s/%s',
            self::randomElement(['channel', 'user']),
            self::regexify(sprintf('[a-zA-Z0-9\-]{1,%s}', self::numberBetween(1, 20)))
        );
    }

    public function youtubeRandomUri(): string
    {
        return match (self::numberBetween(1, 3)) {
            1 => $this->youtubeShortUri(),
            2 => $this->youtubeEmbedUri(),
            default => $this->youtubeUri(),
        };
    }

    public function localImage($ratio = '16x9', $sourceDir = null): string
    {
        $ratio = str_replace(':', 'x', $ratio);
        if (!in_array($ratio, ['1x1', '4x3', '3x4', '9x16', '3x2', '16x9', '21x9'], true)) {
            throw new InvalidArgumentException(sprintf('Invalid ratio "%s"', $ratio));
        }

        if (! $sourceDir) {
            $sourceDir = __DIR__ . "/../../resources/faker/images/{$ratio}/";
        }

        return fake()->file($sourceDir);
    }

    public function localFile($sourceDir = null): string
    {
        if (! $sourceDir) {
            $sourceDir = __DIR__ . '/../../resources/faker/pdfs/';
        }

        return fake()->file($sourceDir);
    }

    public function tags($max = 3, $allowed = []): array
    {
        if (! count($allowed)) {
            $allowed = [
                'Economia',
                'Financiamento',
                'Projetos',
                'Sustentabilidade',
                'Tendências',
            ];
        }

        return fake()->randomElements($allowed, fake()->numberBetween(1, $max));
    }

    public function htmlParagraph($nbSentences = 3): string
    {
        return '<p>' . fake()->paragraph($nbSentences) . '</p>';
    }

    public function htmlParagraphs($nbParagraphs = 10): string
    {
        return collect(range(1, $nbParagraphs))
            ->map(fn () => fake()->paragraph(10))
            ->map(fn ($paragraph) => $this->saltTags($paragraph))
            ->map(fn ($paragraph) => "<p>{$paragraph}</p>")
            ->implode('');
    }

    public function htmlText(): string
    {
        $blocks[] = $this->htmlParagraphs(fake()->numberBetween(3, 6));
        $blocks[] = sprintf("<p><img src=\"%s\" width=\"800\" style=\"width\: 800; height\: 600;\" height=\"600\" data-id=\"%s\"></p>", 'https://picsum.photos/800/600?random=' . random_int(10000, 15999), fake()->uuid());
        $blocks[] = sprintf('<blockquote>%s</blockquote>', $this->htmlParagraphs(fake()->numberBetween(1, 3)));
        $blocks[] = sprintf('<details><summary>%s</summary><div data-type="detailsContent">%s</div></details>', fake()->sentence(3), $this->htmlParagraphs(fake()->numberBetween(1, 3)));

        return implode('', $blocks);
    }

    public function icon(): string
    {
        $icons = [
            'c-academic-cap',
            'c-adjustments-horizontal',
            'c-adjustments-vertical',
            'c-archive-box',
            'c-archive-box-x-mark',
            'c-at-symbol',
            'c-backspace',
            'c-backward',
            'c-banknotes',
            'c-battery-0',
            'c-battery-50',
            'c-battery-100',
            'c-beaker',
            'c-bell',
            'c-bell-alert',
            'c-bell-slash',
            'c-bell-snooze',
            'c-bold',
            'c-bolt',
            'c-bolt-slash',
            'c-bookmark',
            'c-bookmark-slash',
            'c-bookmark-square',
            'c-briefcase',
            'c-bug-ant',
            'c-building-library',
            'c-building-office',
            'c-building-office-2',
            'c-building-storefront',
            'c-cake',
            'c-calculator',
            'c-calendar',
            'c-calendar-date-range',
            'c-calendar-days',
            'c-camera',
            'c-chart-bar',
            'c-chart-bar-square',
            'c-chart-pie',
            'c-chat-bubble-bottom-center',
            'c-chat-bubble-bottom-center-text',
            'c-check',
            'c-check-badge',
            'c-check-circle',
            'c-circle-stack',
            'c-clipboard',
            'c-clock',
            'c-cloud',
            'c-code-bracket',
            'c-code-bracket-square',
            'c-command-line',
            'c-computer-desktop',
            'c-cpu-chip',
            'c-credit-card',
            'c-cube',
            'c-cube-transparent',
            'c-currency-bangladeshi',
            'c-currency-dollar',
            'c-currency-euro',
            'c-currency-pound',
            'c-currency-rupee',
            'c-currency-yen',
            'c-device-phone-mobile',
            'c-device-tablet',
            'c-divide',
            'c-ellipsis-horizontal',
            'c-ellipsis-horizontal-circle',
            'c-ellipsis-vertical',
            'c-envelope',
            'c-equals',
            'c-exclamation-circle',
            'c-exclamation-triangle',
            'c-eye',
            'c-eye-dropper',
            'c-eye-slash',
            'c-face-frown',
            'c-face-smile',
            'c-film',
            'c-finger-print',
            'c-fire',
            'c-flag',
            'c-folder',
            'c-forward',
            'c-funnel',
            'c-gif',
            'c-gift',
            'c-gift-top',
            'c-globe-alt',
            'c-globe-americas',
            'c-globe-asia-australia',
            'c-globe-europe-africa',
            'c-h1',
            'c-h2',
            'c-h3',
            'c-hand-raised',
            'c-hashtag',
            'c-heart',
            'c-home',
            'c-home-modern',
            'c-identification',
            'c-inbox',
            'c-inbox-stack',
            'c-information-circle',
            'c-italic',
            'c-key',
            'c-language',
            'c-lifebuoy',
            'c-light-bulb',
            'c-link',
            'c-link-slash',
            'c-list-bullet',
            'c-lock-closed',
            'c-magnifying-glass',
            'c-magnifying-glass-circle',
            'c-map',
            'c-map-pin',
            'c-megaphone',
            'c-microphone',
            'c-moon',
            'c-musical-note',
            'c-newspaper',
            'c-no-symbol',
            'c-numbered-list',
            'c-paint-brush',
            'c-paper-airplane',
            'c-paper-clip',
            'c-pause',
            'c-pause-circle',
            'c-pencil',
            'c-pencil-square',
            'c-percent-badge',
            'c-phone',
            'c-phone-x-mark',
            'c-photo',
            'c-play',
            'c-play-circle',
            'c-play-pause',
            'c-power',
            'c-presentation-chart-bar',
            'c-presentation-chart-line',
            'c-printer',
            'c-puzzle-piece',
            'c-qr-code',
            'c-question-mark-circle',
            'c-queue-list',
            'c-radio',
            'c-receipt-percent',
            'c-receipt-refund',
            'c-rectangle-group',
            'c-rectangle-stack',
            'c-rocket-launch',
            'c-rss',
            'c-scale',
            'c-scissors',
            'c-server',
            'c-server-stack',
            'c-share',
            'c-shield-check',
            'c-shield-exclamation',
            'c-shopping-bag',
            'c-shopping-cart',
            'c-signal',
            'c-signal-slash',
            'c-slash',
            'c-sparkles',
            'c-speaker-wave',
            'c-speaker-x-mark',
            'c-square-2-stack',
            'c-square-3-stack-3d',
            'c-squares-2x2',
            'c-star',
            'c-stop',
            'c-stop-circle',
            'c-strikethrough',
            'c-sun',
            'c-swatch',
            'c-table-cells',
            'c-tag',
            'c-ticket',
            'c-trash',
            'c-trophy',
            'c-truck',
            'c-tv',
            'c-underline',
            'c-user',
            'c-user-circle',
            'c-user-group',
            'c-users',
            'c-variable',
            'c-video-camera',
            'c-video-camera-slash',
            'c-view-columns',
            'c-viewfinder-circle',
            'c-wallet',
            'c-wifi',
            'c-window',
            'c-wrench',
            'c-wrench-screwdriver',
            'c-x-circle',
            'c-x-mark',
            'm-academic-cap',
            'm-adjustments-horizontal',
            'm-adjustments-vertical',
            'm-archive-box',
            'm-archive-box-x-mark',
            'm-at-symbol',
            'm-backspace',
            'm-backward',
            'm-banknotes',
            'm-battery-0',
            'm-battery-50',
            'm-battery-100',
            'm-beaker',
            'm-bell',
            'm-bell-alert',
            'm-bell-slash',
            'm-bell-snooze',
            'm-bold',
            'm-bolt',
            'm-bolt-slash',
            'm-bookmark',
            'm-bookmark-slash',
            'm-bookmark-square',
            'm-briefcase',
            'm-bug-ant',
            'm-building-library',
            'm-building-office',
            'm-building-office-2',
            'm-building-storefront',
            'm-cake',
            'm-calculator',
            'm-calendar',
            'm-calendar-date-range',
            'm-calendar-days',
            'm-camera',
            'm-chart-bar',
            'm-chart-bar-square',
            'm-chart-pie',
            'm-chat-bubble-bottom-center',
            'm-chat-bubble-bottom-center-text',
            'm-check',
            'm-check-badge',
            'm-check-circle',
            'm-circle-stack',
            'm-clipboard',
            'm-clock',
            'm-cloud',
            'm-code-bracket',
            'm-code-bracket-square',
            'm-command-line',
            'm-computer-desktop',
            'm-cpu-chip',
            'm-credit-card',
            'm-cube',
            'm-cube-transparent',
            'm-currency-bangladeshi',
            'm-currency-dollar',
            'm-currency-euro',
            'm-currency-pound',
            'm-currency-rupee',
            'm-currency-yen',
            'm-device-phone-mobile',
            'm-device-tablet',
            'm-divide',
            'm-ellipsis-horizontal',
            'm-ellipsis-horizontal-circle',
            'm-ellipsis-vertical',
            'm-envelope',
            'm-equals',
            'm-exclamation-circle',
            'm-exclamation-triangle',
            'm-eye',
            'm-eye-dropper',
            'm-eye-slash',
            'm-face-frown',
            'm-face-smile',
            'm-film',
            'm-finger-print',
            'm-fire',
            'm-flag',
            'm-folder',
            'm-forward',
            'm-funnel',
            'm-gif',
            'm-gift',
            'm-gift-top',
            'm-globe-alt',
            'm-globe-americas',
            'm-globe-asia-australia',
            'm-globe-europe-africa',
            'm-h1',
            'm-h2',
            'm-h3',
            'm-hand-raised',
            'm-hashtag',
            'm-heart',
            'm-home',
            'm-home-modern',
            'm-identification',
            'm-inbox',
            'm-inbox-stack',
            'm-information-circle',
            'm-italic',
            'm-key',
            'm-language',
            'm-lifebuoy',
            'm-light-bulb',
            'm-link',
            'm-link-slash',
            'm-list-bullet',
            'm-lock-closed',
            'm-magnifying-glass',
            'm-magnifying-glass-circle',
            'm-map',
            'm-map-pin',
            'm-megaphone',
            'm-microphone',
            'm-moon',
            'm-musical-note',
            'm-newspaper',
            'm-no-symbol',
            'm-numbered-list',
            'm-paint-brush',
            'm-paper-airplane',
            'm-paper-clip',
            'm-pause',
            'm-pause-circle',
            'm-pencil',
            'm-pencil-square',
            'm-percent-badge',
            'm-phone',
            'm-phone-x-mark',
            'm-photo',
            'm-play',
            'm-play-circle',
            'm-play-pause',
            'm-power',
            'm-presentation-chart-bar',
            'm-presentation-chart-line',
            'm-printer',
            'm-puzzle-piece',
            'm-qr-code',
            'm-question-mark-circle',
            'm-queue-list',
            'm-radio',
            'm-receipt-percent',
            'm-receipt-refund',
            'm-rectangle-group',
            'm-rectangle-stack',
            'm-rocket-launch',
            'm-rss',
            'm-scale',
            'm-scissors',
            'm-server',
            'm-server-stack',
            'm-share',
            'm-shield-check',
            'm-shield-exclamation',
            'm-shopping-bag',
            'm-shopping-cart',
            'm-signal',
            'm-signal-slash',
            'm-slash',
            'm-sparkles',
            'm-speaker-wave',
            'm-speaker-x-mark',
            'm-square-2-stack',
            'm-square-3-stack-3d',
            'm-squares-2x2',
            'm-star',
            'm-stop',
            'm-stop-circle',
            'm-strikethrough',
            'm-sun',
            'm-swatch',
            'm-table-cells',
            'm-tag',
            'm-ticket',
            'm-trash',
            'm-trophy',
            'm-truck',
            'm-tv',
            'm-underline',
            'm-user',
            'm-user-circle',
            'm-user-group',
            'm-users',
            'm-variable',
            'm-video-camera',
            'm-video-camera-slash',
            'm-view-columns',
            'm-viewfinder-circle',
            'm-wallet',
            'm-wifi',
            'm-window',
            'm-wrench',
            'm-wrench-screwdriver',
            'm-x-circle',
            'm-x-mark',
            'o-academic-cap',
            'o-adjustments-horizontal',
            'o-adjustments-vertical',
            'o-archive-box',
            'o-archive-box-x-mark',
            'o-at-symbol',
            'o-backspace',
            'o-backward',
            'o-banknotes',
            'o-battery-0',
            'o-battery-50',
            'o-battery-100',
            'o-beaker',
            'o-bell',
            'o-bell-alert',
            'o-bell-slash',
            'o-bell-snooze',
            'o-bold',
            'o-bolt',
            'o-bolt-slash',
            'o-bookmark',
            'o-bookmark-slash',
            'o-bookmark-square',
            'o-briefcase',
            'o-bug-ant',
            'o-building-library',
            'o-building-office',
            'o-building-office-2',
            'o-building-storefront',
            'o-cake',
            'o-calculator',
            'o-calendar',
            'o-calendar-date-range',
            'o-calendar-days',
            'o-camera',
            'o-chart-bar',
            'o-chart-bar-square',
            'o-chart-pie',
            'o-chat-bubble-bottom-center',
            'o-chat-bubble-bottom-center-text',
            'o-check',
            'o-check-badge',
            'o-check-circle',
            'o-circle-stack',
            'o-clipboard',
            'o-clock',
            'o-cloud',
            'o-code-bracket',
            'o-code-bracket-square',
            'o-command-line',
            'o-computer-desktop',
            'o-cpu-chip',
            'o-credit-card',
            'o-cube',
            'o-cube-transparent',
            'o-currency-bangladeshi',
            'o-currency-dollar',
            'o-currency-euro',
            'o-currency-pound',
            'o-currency-rupee',
            'o-currency-yen',
            'o-device-phone-mobile',
            'o-device-tablet',
            'o-divide',
            'o-ellipsis-horizontal',
            'o-ellipsis-horizontal-circle',
            'o-ellipsis-vertical',
            'o-envelope',
            'o-equals',
            'o-exclamation-circle',
            'o-exclamation-triangle',
            'o-eye',
            'o-eye-dropper',
            'o-eye-slash',
            'o-face-frown',
            'o-face-smile',
            'o-film',
            'o-finger-print',
            'o-fire',
            'o-flag',
            'o-folder',
            'o-forward',
            'o-funnel',
            'o-gif',
            'o-gift',
            'o-gift-top',
            'o-globe-alt',
            'o-globe-americas',
            'o-globe-asia-australia',
            'o-globe-europe-africa',
            'o-h1',
            'o-h2',
            'o-h3',
            'o-hand-raised',
            'o-hashtag',
            'o-heart',
            'o-home',
            'o-home-modern',
            'o-identification',
            'o-inbox',
            'o-inbox-stack',
            'o-information-circle',
            'o-italic',
            'o-key',
            'o-language',
            'o-lifebuoy',
            'o-light-bulb',
            'o-link',
            'o-link-slash',
            'o-list-bullet',
            'o-lock-closed',
            'o-magnifying-glass',
            'o-magnifying-glass-circle',
            'o-map',
            'o-map-pin',
            'o-megaphone',
            'o-microphone',
            'o-moon',
            'o-musical-note',
            'o-newspaper',
            'o-no-symbol',
            'o-numbered-list',
            'o-paint-brush',
            'o-paper-airplane',
            'o-paper-clip',
            'o-pause',
            'o-pause-circle',
            'o-pencil',
            'o-pencil-square',
            'o-percent-badge',
            'o-phone',
            'o-phone-x-mark',
            'o-photo',
            'o-play',
            'o-play-circle',
            'o-play-pause',
            'o-power',
            'o-presentation-chart-bar',
            'o-presentation-chart-line',
            'o-printer',
            'o-puzzle-piece',
            'o-qr-code',
            'o-question-mark-circle',
            'o-queue-list',
            'o-radio',
            'o-receipt-percent',
            'o-receipt-refund',
            'o-rectangle-group',
            'o-rectangle-stack',
            'o-rocket-launch',
            'o-rss',
            'o-scale',
            'o-scissors',
            'o-server',
            'o-server-stack',
            'o-share',
            'o-shield-check',
            'o-shield-exclamation',
            'o-shopping-bag',
            'o-shopping-cart',
            'o-signal',
            'o-signal-slash',
            'o-slash',
            'o-sparkles',
            'o-speaker-wave',
            'o-speaker-x-mark',
            'o-square-2-stack',
            'o-square-3-stack-3d',
            'o-squares-2x2',
            'o-star',
            'o-stop',
            'o-stop-circle',
            'o-strikethrough',
            'o-sun',
            'o-swatch',
            'o-table-cells',
            'o-tag',
            'o-ticket',
            'o-trash',
            'o-trophy',
            'o-truck',
            'o-tv',
            'o-underline',
            'o-user',
            'o-user-circle',
            'o-user-group',
            'o-users',
            'o-variable',
            'o-video-camera',
            'o-video-camera-slash',
            'o-view-columns',
            'o-viewfinder-circle',
            'o-wallet',
            'o-wifi',
            'o-window',
            'o-wrench',
            'o-wrench-screwdriver',
            'o-x-circle',
            'o-x-mark',
            's-academic-cap',
            's-adjustments-horizontal',
            's-adjustments-vertical',
            's-archive-box',
            's-archive-box-x-mark',
            's-at-symbol',
            's-backspace',
            's-backward',
            's-banknotes',
            's-battery-0',
            's-battery-50',
            's-battery-100',
            's-beaker',
            's-bell',
            's-bell-alert',
            's-bell-slash',
            's-bell-snooze',
            's-bold',
            's-bolt',
            's-bolt-slash',
            's-bookmark',
            's-bookmark-slash',
            's-bookmark-square',
            's-briefcase',
            's-bug-ant',
            's-building-library',
            's-building-office',
            's-building-office-2',
            's-building-storefront',
            's-cake',
            's-calculator',
            's-calendar',
            's-calendar-date-range',
            's-calendar-days',
            's-camera',
            's-chart-bar',
            's-chart-bar-square',
            's-chart-pie',
            's-chat-bubble-bottom-center',
            's-chat-bubble-bottom-center-text',
            's-check',
            's-check-badge',
            's-check-circle',
            's-circle-stack',
            's-clipboard',
            's-clock',
            's-cloud',
            's-code-bracket',
            's-code-bracket-square',
            's-command-line',
            's-computer-desktop',
            's-cpu-chip',
            's-credit-card',
            's-cube',
            's-cube-transparent',
            's-currency-bangladeshi',
            's-currency-dollar',
            's-currency-euro',
            's-currency-pound',
            's-currency-rupee',
            's-currency-yen',
            's-device-phone-mobile',
            's-device-tablet',
            's-divide',
            's-ellipsis-horizontal',
            's-ellipsis-horizontal-circle',
            's-ellipsis-vertical',
            's-envelope',
            's-equals',
            's-exclamation-circle',
            's-exclamation-triangle',
            's-eye',
            's-eye-dropper',
            's-eye-slash',
            's-face-frown',
            's-face-smile',
            's-film',
            's-finger-print',
            's-fire',
            's-flag',
            's-folder',
            's-forward',
            's-funnel',
            's-gif',
            's-gift',
            's-gift-top',
            's-globe-alt',
            's-globe-americas',
            's-globe-asia-australia',
            's-globe-europe-africa',
            's-h1',
            's-h2',
            's-h3',
            's-hand-raised',
            's-hashtag',
            's-heart',
            's-home',
            's-home-modern',
            's-identification',
            's-inbox',
            's-inbox-stack',
            's-information-circle',
            's-italic',
            's-key',
            's-language',
            's-lifebuoy',
            's-light-bulb',
            's-link',
            's-link-slash',
            's-list-bullet',
            's-lock-closed',
            's-magnifying-glass',
            's-magnifying-glass-circle',
            's-map',
            's-map-pin',
            's-megaphone',
            's-microphone',
            's-moon',
            's-musical-note',
            's-newspaper',
            's-no-symbol',
            's-numbered-list',
            's-paint-brush',
            's-paper-airplane',
            's-paper-clip',
            's-pause',
            's-pause-circle',
            's-pencil',
            's-pencil-square',
            's-percent-badge',
            's-phone',
            's-phone-x-mark',
            's-photo',
            's-play',
            's-play-circle',
            's-play-pause',
            's-power',
            's-presentation-chart-bar',
            's-presentation-chart-line',
            's-printer',
            's-puzzle-piece',
            's-qr-code',
            's-question-mark-circle',
            's-queue-list',
            's-radio',
            's-receipt-percent',
            's-receipt-refund',
            's-rectangle-group',
            's-rectangle-stack',
            's-rocket-launch',
            's-rss',
            's-scale',
            's-scissors',
            's-server',
            's-server-stack',
            's-share',
            's-shield-check',
            's-shield-exclamation',
            's-shopping-bag',
            's-shopping-cart',
            's-signal',
            's-signal-slash',
            's-slash',
            's-sparkles',
            's-speaker-wave',
            's-speaker-x-mark',
            's-square-2-stack',
            's-square-3-stack-3d',
            's-squares-2x2',
            's-star',
            's-stop',
            's-stop-circle',
            's-strikethrough',
            's-sun',
            's-swatch',
            's-table-cells',
            's-tag',
            's-ticket',
            's-trash',
            's-trophy',
            's-truck',
            's-tv',
            's-underline',
            's-user',
            's-user-circle',
            's-user-group',
            's-users',
            's-variable',
            's-video-camera',
            's-video-camera-slash',
            's-view-columns',
            's-viewfinder-circle',
            's-wallet',
            's-wifi',
            's-window',
            's-wrench',
            's-wrench-screwdriver',
            's-x-circle',
            's-x-mark',
        ];

        return 'heroicon-' . collect($icons)
                ->random(1)->first();
    }

    private function saltTags($text, $nbTags = 3): string
    {
        $tags = [
            '<strong>%s</strong>',
            '<em>%s</em>',
            '<u>%s</u>',
            '<s>%s</s>',
            '<a href="https://fmd.ag">%s</a>',
        ];
        shuffle($tags);
        $words = explode(' ', $text);
        shuffle($words);
        $taggedWords = [];
        for ($i = 0; $i < $nbTags; $i++) {
            $taggedWords[$words[$i]] = sprintf($tags[$i], $words[$i]);
        }

        return str_replace(array_keys($taggedWords), array_values($taggedWords), $text);
    }
}
